Revert gitlab-ci to previous version

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -72,8 +72,9 @@ review:
   script:
     - check_kube_domain
     - install_dependencies
-    - update_chart_deps
+    - download_chart
     - ensure_namespace
+    - install_tiller
     - create_secret
     - deploy review
     - persist_environment_url
@@ -114,8 +115,9 @@ production:
   script:
     - check_kube_domain
     - install_dependencies
-    - update_chart_deps
+    - download_chart
     - ensure_namespace
+    - install_tiller
     - create_secret
     - deploy
     - persist_environment_url
@@ -137,6 +139,7 @@ production:
   export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
   export CI_APPLICATION_TAG=$CI_COMMIT_SHA
   export CI_CONTAINER_NAME=ci_job_build_${CI_JOB_ID}
+  export TILLER_NAMESPACE=gitlab-managed-apps
 
   function get_replicas() {
     track="${1:-stable}"
@@ -232,7 +235,25 @@ production:
     fi
   }
 
-  function update_chart_deps() {
+  function download_chart() {
+    if [[ ! -d chart ]]; then
+      auto_chart=${AUTO_DEVOPS_CHART:-gitlab/auto-deploy-app}
+      auto_chart_name=$(basename $auto_chart)
+      auto_chart_name=${auto_chart_name%.tgz}
+    else
+      auto_chart="chart"
+      auto_chart_name="chart"
+    fi
+
+    helm init --client-only
+    helm repo add gitlab https://charts.gitlab.io
+    if [[ ! -d "$auto_chart" ]]; then
+      helm fetch ${auto_chart} --untar
+    fi
+    if [ "$auto_chart_name" != "chart" ]; then
+      mv ${auto_chart_name} chart
+    fi
+
     helm dependency update chart/
     helm dependency build chart/
   }
@@ -288,6 +309,17 @@ production:
 
     echo "Pushing to GitLab Container Registry..."
     docker push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
+    echo ""
+  }
+
+  function install_tiller() {
+    echo "Checking Tiller..."
+    helm init --upgrade
+    kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
+    if ! helm version --debug; then
+      echo "Failed to init Tiller."
+      return 1
+    fi
     echo ""
   }
 
